ood_dataset:
  name: imagenet200_fsood
  num_classes: 200

  dataset_class: ImglistDataset
  interpolation: bilinear
  batch_size: 256
  shuffle: False

  pre_size: 256
  image_size: 224
  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'
  split_names: [val, nearood, farood, csid]
  val:
    data_dir: $YOUR_DATASET_PATH/
    imglist_pth: $YOUR_DATASET_PATH/benchmark_imglist/imagenet200/val_openimage_o.txt
  nearood:
    datasets: [ssb_hard, ninco]
    ssb_hard:
      data_dir: $YOUR_DATASET_PATH/
      imglist_pth: $YOUR_DATASET_PATH/benchmark_imglist/imagenet/test_ssb_hard.txt
    ninco:
      data_dir: $YOUR_DATASET_PATH/
      imglist_pth: $YOUR_DATASET_PATH/benchmark_imglist/imagenet/test_ninco.txt
  farood:
    datasets: [inaturalist, textures, openimageo]
    textures:
      data_dir: $YOUR_DATASET_PATH/images_classic/
      imglist_pth: $YOUR_DATASET_PATH/benchmark_imglist/imagenet/test_textures.txt
    inaturalist:
      data_dir: $YOUR_DATASET_PATH/
      imglist_pth: $YOUR_DATASET_PATH/benchmark_imglist/imagenet/test_inaturalist.txt
    openimageo:
      data_dir: $YOUR_DATASET_PATH/
      imglist_pth: $YOUR_DATASET_PATH/benchmark_imglist/imagenet/test_openimage_o.txt
  csid:
    datasets: [imagenetv2, imagenetc, imagenetr]
    imagenetv2:
      data_dir: $YOUR_DATASET_PATH/
      imglist_pth: $YOUR_DATASET_PATH/benchmark_imglist/imagenet200/test_imagenet200_v2_mos.txt
    imagenetc:
      data_dir: $YOUR_DATASET_PATH/
      imglist_pth: $YOUR_DATASET_PATH/benchmark_imglist/imagenet200/test_imagenet200_c_mos.txt
    imagenetr:
      data_dir: $YOUR_DATASET_PATH/
      imglist_pth: $YOUR_DATASET_PATH/benchmark_imglist/imagenet200/test_imagenet200_r_mos.txt
