test_subset:
    name: "LT100"
    id:
        mode: "LT"
        order: "normal"
        imb_factor: 0.01
    csid:
        mode: "LT"
        order: "normal"
        imb_factor: 0.01
    ood:
        mode: "Reduce"
        order: "normal"
        ratio: 1.0