test_subset:
    name: "LT10"
    id:
        mode: "LT"
        order: "normal"
        imb_factor: 0.1
    csid:
        mode: "LT"
        order: "normal"
        imb_factor: 0.1
    ood:
        mode: "Reduce"
        order: "normal"
        ratio: 1.0