test_subset:
    name: "LT5"
    id:
        mode: "LT"
        order: "normal"
        imb_factor: 0.2
    csid:
        mode: "LT"
        order: "normal"
        imb_factor: 0.2
    ood:
        mode: "Reduce"
        order: "normal"
        ratio: 1.0