test_subset:
    name: "Dir10"
    id:
        mode: "Dirichlet"
        order: "normal"
        dirichlet_alpha: 10.0
        total_num: 2500
    csid:
        mode: "Dirichlet"
        order: "normal"
        dirichlet_alpha: 10.0
        total_num: 2500
    ood:
        mode: "Reduce"
        order: "normal"
        ratio: 1.0

