network:
  name: resnet32
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: False          # set 'True' to load pretrained model
  checkpoint: ./checkpoints/resnet50-0676ba61.pth           # ignore if pretrained is false
  num_gpus: '@{num_gpus}'