test_subset:
    name: "Shuffle100"
    id:
        mode: "LT"
        order: "random"
        imb_factor: 0.01
    csid:
        mode: "LT"
        order: "random"
        imb_factor: 0.01
    ood:
        mode: "Reduce"
        order: "normal"
        ratio: 1.0