test_subset:
    name: "Shuffle20"
    id:
        mode: "LT"
        order: "random"
        imb_factor: 0.05
    csid:
        mode: "LT"
        order: "random"
        imb_factor: 0.05
    ood:
        mode: "Reduce"
        order: "normal"
        ratio: 1.0