postprocessor:
  name: ensemble
  postprocessor_args:
    network_name: lenet
    checkpoint_root: $YOUR_CHECKPOINT_PATH/lenet_ensemble_pretrained
    checkpoints: [net1, net2, net3, net4, net5]
    num_networks: 5  # number of networks to ensembel
