postprocessor:
  name: ensemble
  postprocessor_args:
    network_name: lenet
    checkpoint_root: /data2/u6469845/LOGS/Baselines/OpenOOD/lenet_ensemble_pretrained
    checkpoints: [net1, net2, net3, net4, net5]
    num_networks: 5  # number of networks to ensembel
