dataset:
  name: imagenet_LT
  num_classes: 1000
  pre_size: 256
  image_size: 224

  interpolation: bilinear
  normalization_type: imagenet

  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [train, val, test]

  train:
    dataset_class: ImglistDataset
    data_dir: $YOUR_DATASET_PATH/images_largescale/imagenet_1k/
    imglist_pth: $YOUR_DATASET_PATH/ImageNet/ImageNet_LT_train.txt
    batch_size: 256
    shuffle: True
  val:
    dataset_class: ImglistDataset
    data_dir: $YOUR_DATASET_PATH/images_largescale/imagenet_1k/
    imglist_pth: $YOUR_DATASET_PATH/ImageNet/ImageNet_LT_val.txt
    batch_size: 128
    shuffle: False
  test:
    dataset_class: ImglistDataset
    data_dir: $YOUR_DATASET_PATH/images_largescale/imagenet_1k/
    imglist_pth: $YOUR_DATASET_PATH/ImageNet/ImageNet_LT_test2.txt
    batch_size: 128
    shuffle: False
