test_subset:
    name: "KnockOut0.7"
    id:
        mode: "KnockOut"
        order: "normal"
        knockout_ratio: 0.7
    csid:
        mode: "KnockOut"
        order: "normal"
        knockout_ratio: 0.7
    ood:
        mode: "Reduce"
        order: "normal"
        ratio: 1.0